language: go

install:
 - sudo apt-get install libpcap0.8-dev
 - go get -d -v ./... && go build -v ./...

script:
 - go test -v ./...

notifications:
  recipient:
   - alessandro@ghedini.me
  email:
    on_success: change
    on_failure: always
